import type { Team, Match } from "./types"

// Datos iniciales de equipos - Primera RFEF Grupo 1 (Temporada 2025-26)
// Clasificación actualizada a Jornada 21 (datos de BDFutbol)
export const initialTeams: Team[] = [
  {
    id: 1,
    name: "CD Tenerife",
    played: 21,
    won: 16,
    drawn: 2,
    lost: 3,
    goalsFor: 40,
    goalsAgainst: 12,
    points: 50,
    logoUrl: "https://tmssl.akamaized.net/images/wappen/medium/648.png?lm=1578091884",
  },
  {
    id: 2,
    name: "RC Celta Fortuna",
    played: 21,
    won: 11,
    drawn: 5,
    lost: 5,
    goalsFor: 33,
    goalsAgainst: 27,
    points: 38,
    logoUrl: "https://tmssl.akamaized.net/images/wappen/medium/8733.png?lm=1406966406",
  },
  {
    id: 3,
    name: "Pontevedra CF",
    played: 21,
    won: 9,
    drawn: 8,
    lost: 4,
    goalsFor: 27,
    goalsAgainst: 18,
    points: 35,
    logoUrl: "https://tmssl.akamaized.net/images/wappen/medium/5650.png?lm=1732278110",
  },
  {
    id: 4,
    name: "Bilbao Athletic",
    played: 21,
    won: 10,
    drawn: 4,
    lost: 7,
    goalsFor: 25,
    goalsAgainst: 25,
    points: 34,
    logoUrl: "https://tmssl.akamaized.net/images/wappen/medium/6688.png?lm=1695069038",
  },
  {
    id: 5,
    name: "Racing Ferrol",
    played: 21,
    won: 10,
    drawn: 3,
    lost: 8,
    goalsFor: 26,
    goalsAgainst: 24,
    points: 33,
    logoUrl: "https://tmssl.akamaized.net/images/wappen/medium/1176.png?lm=1702049971",
  },
  {
    id: 6,
    name: "Real Madrid Castilla",
    played: 21,
    won: 10,
    drawn: 2,
    lost: 9,
    goalsFor: 28,
    goalsAgainst: 30,
    points: 32,
    logoUrl: "https://tmssl.akamaized.net/images/wappen/medium/6767.png?lm=1729684474",
  },
  {
    id: 7,
    name: "CD Lugo",
    played: 21,
    won: 8,
    drawn: 8,
    lost: 5,
    goalsFor: 21,
    goalsAgainst: 18,
    points: 32,
    logoUrl: "https://tmssl.akamaized.net/images/wappen/medium/11000.png?lm=1405933427",
  },
  {
    id: 8,
    name: "Zamora CF",
    played: 21,
    won: 8,
    drawn: 7,
    lost: 6,
    goalsFor: 29,
    goalsAgainst: 25,
    points: 31,
    logoUrl: "https://tmssl.akamaized.net/images/wappen/medium/10907.png?lm=1422972812",
  },
  {
    id: 9,
    name: "Real Avilés Industrial",
    played: 21,
    won: 9,
    drawn: 3,
    lost: 9,
    goalsFor: 30,
    goalsAgainst: 30,
    points: 30,
    logoUrl: "https://tmssl.akamaized.net/images/wappen/medium/20844.png?lm=1705039777",
  },
  {
    id: 10,
    name: "Barakaldo CF",
    played: 21,
    won: 7,
    drawn: 8,
    lost: 6,
    goalsFor: 28,
    goalsAgainst: 24,
    points: 29,
    logoUrl: "https://tmssl.akamaized.net/images/wappen/medium/3708.png?lm=1422971751",
  },
  {
    id: 11,
    name: "Mérida AD",
    played: 21,
    won: 8,
    drawn: 5,
    lost: 8,
    goalsFor: 29,
    goalsAgainst: 29,
    points: 29,
    logoUrl: "https://tmssl.akamaized.net/images/wappen/medium/46854.png?lm=1718102950",
  },
  {
    id: 12,
    name: "Unionistas CF",
    played: 21,
    won: 7,
    drawn: 6,
    lost: 8,
    goalsFor: 29,
    goalsAgainst: 28,
    points: 27,
    logoUrl: "https://tmssl.akamaized.net/images/wappen/medium/52397.png?lm=1468618498",
  },
  {
    id: 13,
    name: "Arenas Club",
    played: 21,
    won: 8,
    drawn: 3,
    lost: 10,
    goalsFor: 26,
    goalsAgainst: 31,
    points: 27,
    logoUrl: "https://tmssl.akamaized.net/images/wappen/medium/16122.png?lm=1706197149",
  },
  {
    id: 14,
    name: "SD Ponferradina",
    played: 21,
    won: 7,
    drawn: 5,
    lost: 9,
    goalsFor: 23,
    goalsAgainst: 22,
    points: 26,
    logoUrl: "https://tmssl.akamaized.net/images/wappen/medium/4032.png?lm=1625561266",
  },
  {
    id: 15,
    name: "Ourense CF",
    played: 21,
    won: 6,
    drawn: 7,
    lost: 8,
    goalsFor: 24,
    goalsAgainst: 26,
    points: 25,
    logoUrl: "https://tmssl.akamaized.net/images/wappen/medium/55398.png?lm=1472936726",
  },
  {
    id: 16,
    name: "CF Talavera de la Reina",
    played: 21,
    won: 6,
    drawn: 4,
    lost: 11,
    goalsFor: 22,
    goalsAgainst: 28,
    points: 22,
    logoUrl: "https://tmssl.akamaized.net/images/wappen/medium/47421.png?lm=1468166961",
  },
  {
    id: 17,
    name: "CP Cacereño",
    played: 21,
    won: 5,
    drawn: 7,
    lost: 9,
    goalsFor: 19,
    goalsAgainst: 28,
    points: 22,
    logoUrl: "https://tmssl.akamaized.net/images/wappen/medium/11602.png?lm=1637151598",
  },
  {
    id: 18,
    name: "CD Arenteiro",
    played: 21,
    won: 5,
    drawn: 5,
    lost: 11,
    goalsFor: 15,
    goalsAgainst: 24,
    points: 20,
    logoUrl: "https://tmssl.akamaized.net/images/wappen/medium/58946.png?lm=1688843561",
  },
  {
    id: 19,
    name: "CA Osasuna Promesas",
    played: 21,
    won: 4,
    drawn: 6,
    lost: 11,
    goalsFor: 14,
    goalsAgainst: 26,
    points: 18,
    logoUrl: "https://tmssl.akamaized.net/images/wappen/medium/8516.png?lm=1686070938",
  },
  {
    id: 20,
    name: "CD Guadalajara",
    played: 21,
    won: 4,
    drawn: 6,
    lost: 11,
    goalsFor: 20,
    goalsAgainst: 33,
    points: 18,
    logoUrl: "https://tmssl.akamaized.net/images/wappen/medium/16576.png?lm=1754924420",
  },
]

// Partidos pendientes - Primera RFEF Grupo 1 (Jornadas 22-38)
// Los emparejamientos se actualizarán con el calendario oficial
export const initialFixtures: Match[] = [
  // Jornada 22
  { id: 1, matchday: 22, homeTeamId: 2, awayTeamId: 12, result: null }, // Celta Fortuna vs Unionistas
  { id: 2, matchday: 22, homeTeamId: 16, awayTeamId: 3, result: null }, // Talavera vs Pontevedra
  { id: 3, matchday: 22, homeTeamId: 1, awayTeamId: 20, result: null }, // Tenerife vs Guadalajara
  { id: 4, matchday: 22, homeTeamId: 8, awayTeamId: 5, result: null }, // Zamora vs Racing Ferrol
  { id: 5, matchday: 22, homeTeamId: 9, awayTeamId: 11, result: null }, // Real Avilés vs Mérida
  { id: 6, matchday: 22, homeTeamId: 13, awayTeamId: 15, result: null }, // Arenas vs Ourense
  { id: 7, matchday: 22, homeTeamId: 17, awayTeamId: 10, result: null }, // Cacereño vs Barakaldo
  { id: 8, matchday: 22, homeTeamId: 7, awayTeamId: 14, result: null }, // Lugo vs Ponferradina
  { id: 9, matchday: 22, homeTeamId: 6, awayTeamId: 19, result: null }, // RM Castilla vs Osasuna B
  { id: 10, matchday: 22, homeTeamId: 18, awayTeamId: 4, result: null }, // Arenteiro vs Bilbao Athletic
  // Jornada 23
  { id: 11, matchday: 23, homeTeamId: 10, awayTeamId: 16, result: null }, // Barakaldo vs Talavera
  { id: 12, matchday: 23, homeTeamId: 4, awayTeamId: 1, result: null }, // Bilbao Athletic vs Tenerife
  { id: 13, matchday: 23, homeTeamId: 18, awayTeamId: 9, result: null }, // Arenteiro vs Real Avilés
  { id: 14, matchday: 23, homeTeamId: 5, awayTeamId: 7, result: null }, // Racing Ferrol vs Lugo
  { id: 15, matchday: 23, homeTeamId: 12, awayTeamId: 15, result: null }, // Unionistas vs Ourense
  { id: 16, matchday: 23, homeTeamId: 19, awayTeamId: 17, result: null }, // Osasuna B vs Cacereño
  { id: 17, matchday: 23, homeTeamId: 3, awayTeamId: 6, result: null }, // Pontevedra vs RM Castilla
  { id: 18, matchday: 23, homeTeamId: 20, awayTeamId: 13, result: null }, // Guadalajara vs Arenas
  { id: 19, matchday: 23, homeTeamId: 11, awayTeamId: 8, result: null }, // Mérida vs Zamora
  { id: 20, matchday: 23, homeTeamId: 14, awayTeamId: 2, result: null }, // Ponferradina vs Celta Fortuna
  // Jornada 24 - Placeholder (actualizar con calendario oficial)
  { id: 21, matchday: 24, homeTeamId: 1, awayTeamId: 5, result: null },
  { id: 22, matchday: 24, homeTeamId: 2, awayTeamId: 4, result: null },
  { id: 23, matchday: 24, homeTeamId: 3, awayTeamId: 8, result: null },
  { id: 24, matchday: 24, homeTeamId: 6, awayTeamId: 10, result: null },
  { id: 25, matchday: 24, homeTeamId: 7, awayTeamId: 11, result: null },
  { id: 26, matchday: 24, homeTeamId: 9, awayTeamId: 12, result: null },
  { id: 27, matchday: 24, homeTeamId: 13, awayTeamId: 14, result: null },
  { id: 28, matchday: 24, homeTeamId: 15, awayTeamId: 16, result: null },
  { id: 29, matchday: 24, homeTeamId: 17, awayTeamId: 18, result: null },
  { id: 30, matchday: 24, homeTeamId: 19, awayTeamId: 20, result: null },
  // Jornada 25 - Placeholder
  { id: 31, matchday: 25, homeTeamId: 4, awayTeamId: 3, result: null },
  { id: 32, matchday: 25, homeTeamId: 5, awayTeamId: 2, result: null },
  { id: 33, matchday: 25, homeTeamId: 8, awayTeamId: 1, result: null },
  { id: 34, matchday: 25, homeTeamId: 10, awayTeamId: 7, result: null },
  { id: 35, matchday: 25, homeTeamId: 11, awayTeamId: 6, result: null },
  { id: 36, matchday: 25, homeTeamId: 12, awayTeamId: 9, result: null },
  { id: 37, matchday: 25, homeTeamId: 14, awayTeamId: 13, result: null },
  { id: 38, matchday: 25, homeTeamId: 16, awayTeamId: 15, result: null },
  { id: 39, matchday: 25, homeTeamId: 18, awayTeamId: 17, result: null },
  { id: 40, matchday: 25, homeTeamId: 20, awayTeamId: 19, result: null },
  // Jornada 26 - Placeholder
  { id: 41, matchday: 26, homeTeamId: 1, awayTeamId: 6, result: null },
  { id: 42, matchday: 26, homeTeamId: 2, awayTeamId: 8, result: null },
  { id: 43, matchday: 26, homeTeamId: 3, awayTeamId: 10, result: null },
  { id: 44, matchday: 26, homeTeamId: 4, awayTeamId: 12, result: null },
  { id: 45, matchday: 26, homeTeamId: 5, awayTeamId: 14, result: null },
  { id: 46, matchday: 26, homeTeamId: 7, awayTeamId: 16, result: null },
  { id: 47, matchday: 26, homeTeamId: 9, awayTeamId: 18, result: null },
  { id: 48, matchday: 26, homeTeamId: 11, awayTeamId: 20, result: null },
  { id: 49, matchday: 26, homeTeamId: 13, awayTeamId: 19, result: null },
  { id: 50, matchday: 26, homeTeamId: 15, awayTeamId: 17, result: null },
  // Jornada 27 - Placeholder
  { id: 51, matchday: 27, homeTeamId: 6, awayTeamId: 2, result: null },
  { id: 52, matchday: 27, homeTeamId: 8, awayTeamId: 4, result: null },
  { id: 53, matchday: 27, homeTeamId: 10, awayTeamId: 1, result: null },
  { id: 54, matchday: 27, homeTeamId: 12, awayTeamId: 3, result: null },
  { id: 55, matchday: 27, homeTeamId: 14, awayTeamId: 7, result: null },
  { id: 56, matchday: 27, homeTeamId: 16, awayTeamId: 9, result: null },
  { id: 57, matchday: 27, homeTeamId: 18, awayTeamId: 11, result: null },
  { id: 58, matchday: 27, homeTeamId: 20, awayTeamId: 5, result: null },
  { id: 59, matchday: 27, homeTeamId: 17, awayTeamId: 13, result: null },
  { id: 60, matchday: 27, homeTeamId: 19, awayTeamId: 15, result: null },
  // Jornada 28 - Placeholder
  { id: 61, matchday: 28, homeTeamId: 1, awayTeamId: 12, result: null },
  { id: 62, matchday: 28, homeTeamId: 2, awayTeamId: 10, result: null },
  { id: 63, matchday: 28, homeTeamId: 3, awayTeamId: 14, result: null },
  { id: 64, matchday: 28, homeTeamId: 4, awayTeamId: 16, result: null },
  { id: 65, matchday: 28, homeTeamId: 5, awayTeamId: 18, result: null },
  { id: 66, matchday: 28, homeTeamId: 7, awayTeamId: 20, result: null },
  { id: 67, matchday: 28, homeTeamId: 6, awayTeamId: 8, result: null },
  { id: 68, matchday: 28, homeTeamId: 9, awayTeamId: 17, result: null },
  { id: 69, matchday: 28, homeTeamId: 11, awayTeamId: 19, result: null },
  { id: 70, matchday: 28, homeTeamId: 13, awayTeamId: 15, result: null },
  // Jornada 29 - Placeholder
  { id: 71, matchday: 29, homeTeamId: 10, awayTeamId: 4, result: null },
  { id: 72, matchday: 29, homeTeamId: 12, awayTeamId: 6, result: null },
  { id: 73, matchday: 29, homeTeamId: 14, awayTeamId: 1, result: null },
  { id: 74, matchday: 29, homeTeamId: 16, awayTeamId: 3, result: null },
  { id: 75, matchday: 29, homeTeamId: 18, awayTeamId: 7, result: null },
  { id: 76, matchday: 29, homeTeamId: 20, awayTeamId: 2, result: null },
  { id: 77, matchday: 29, homeTeamId: 8, awayTeamId: 5, result: null },
  { id: 78, matchday: 29, homeTeamId: 15, awayTeamId: 11, result: null },
  { id: 79, matchday: 29, homeTeamId: 17, awayTeamId: 9, result: null },
  { id: 80, matchday: 29, homeTeamId: 19, awayTeamId: 13, result: null },
  // Jornada 30 - Placeholder
  { id: 81, matchday: 30, homeTeamId: 1, awayTeamId: 16, result: null },
  { id: 82, matchday: 30, homeTeamId: 2, awayTeamId: 14, result: null },
  { id: 83, matchday: 30, homeTeamId: 3, awayTeamId: 18, result: null },
  { id: 84, matchday: 30, homeTeamId: 4, awayTeamId: 20, result: null },
  { id: 85, matchday: 30, homeTeamId: 5, awayTeamId: 10, result: null },
  { id: 86, matchday: 30, homeTeamId: 6, awayTeamId: 12, result: null },
  { id: 87, matchday: 30, homeTeamId: 7, awayTeamId: 8, result: null },
  { id: 88, matchday: 30, homeTeamId: 9, awayTeamId: 15, result: null },
  { id: 89, matchday: 30, homeTeamId: 11, awayTeamId: 17, result: null },
  { id: 90, matchday: 30, homeTeamId: 13, awayTeamId: 19, result: null },
  // Jornada 31 - Placeholder
  { id: 91, matchday: 31, homeTeamId: 8, awayTeamId: 1, result: null },
  { id: 92, matchday: 31, homeTeamId: 10, awayTeamId: 3, result: null },
  { id: 93, matchday: 31, homeTeamId: 12, awayTeamId: 7, result: null },
  { id: 94, matchday: 31, homeTeamId: 14, awayTeamId: 4, result: null },
  { id: 95, matchday: 31, homeTeamId: 16, awayTeamId: 6, result: null },
  { id: 96, matchday: 31, homeTeamId: 18, awayTeamId: 2, result: null },
  { id: 97, matchday: 31, homeTeamId: 20, awayTeamId: 9, result: null },
  { id: 98, matchday: 31, homeTeamId: 15, awayTeamId: 5, result: null },
  { id: 99, matchday: 31, homeTeamId: 17, awayTeamId: 11, result: null },
  { id: 100, matchday: 31, homeTeamId: 19, awayTeamId: 13, result: null },
  // Jornada 32 - Placeholder
  { id: 101, matchday: 32, homeTeamId: 1, awayTeamId: 20, result: null },
  { id: 102, matchday: 32, homeTeamId: 2, awayTeamId: 16, result: null },
  { id: 103, matchday: 32, homeTeamId: 3, awayTeamId: 12, result: null },
  { id: 104, matchday: 32, homeTeamId: 4, awayTeamId: 18, result: null },
  { id: 105, matchday: 32, homeTeamId: 5, awayTeamId: 6, result: null },
  { id: 106, matchday: 32, homeTeamId: 7, awayTeamId: 10, result: null },
  { id: 107, matchday: 32, homeTeamId: 9, awayTeamId: 14, result: null },
  { id: 108, matchday: 32, homeTeamId: 11, awayTeamId: 8, result: null },
  { id: 109, matchday: 32, homeTeamId: 13, awayTeamId: 17, result: null },
  { id: 110, matchday: 32, homeTeamId: 15, awayTeamId: 19, result: null },
  // Jornada 33 - Placeholder
  { id: 111, matchday: 33, homeTeamId: 6, awayTeamId: 1, result: null },
  { id: 112, matchday: 33, homeTeamId: 8, awayTeamId: 3, result: null },
  { id: 113, matchday: 33, homeTeamId: 10, awayTeamId: 9, result: null },
  { id: 114, matchday: 33, homeTeamId: 12, awayTeamId: 2, result: null },
  { id: 115, matchday: 33, homeTeamId: 14, awayTeamId: 11, result: null },
  { id: 116, matchday: 33, homeTeamId: 16, awayTeamId: 5, result: null },
  { id: 117, matchday: 33, homeTeamId: 18, awayTeamId: 7, result: null },
  { id: 118, matchday: 33, homeTeamId: 20, awayTeamId: 4, result: null },
  { id: 119, matchday: 33, homeTeamId: 17, awayTeamId: 15, result: null },
  { id: 120, matchday: 33, homeTeamId: 19, awayTeamId: 13, result: null },
  // Jornada 34 - Placeholder
  { id: 121, matchday: 34, homeTeamId: 1, awayTeamId: 18, result: null },
  { id: 122, matchday: 34, homeTeamId: 2, awayTeamId: 20, result: null },
  { id: 123, matchday: 34, homeTeamId: 3, awayTeamId: 6, result: null },
  { id: 124, matchday: 34, homeTeamId: 4, awayTeamId: 10, result: null },
  { id: 125, matchday: 34, homeTeamId: 5, awayTeamId: 12, result: null },
  { id: 126, matchday: 34, homeTeamId: 7, awayTeamId: 14, result: null },
  { id: 127, matchday: 34, homeTeamId: 9, awayTeamId: 16, result: null },
  { id: 128, matchday: 34, homeTeamId: 11, awayTeamId: 15, result: null },
  { id: 129, matchday: 34, homeTeamId: 13, awayTeamId: 17, result: null },
  { id: 130, matchday: 34, homeTeamId: 8, awayTeamId: 19, result: null },
  // Jornada 35 - Placeholder
  { id: 131, matchday: 35, homeTeamId: 6, awayTeamId: 4, result: null },
  { id: 132, matchday: 35, homeTeamId: 10, awayTeamId: 2, result: null },
  { id: 133, matchday: 35, homeTeamId: 12, awayTeamId: 1, result: null },
  { id: 134, matchday: 35, homeTeamId: 14, awayTeamId: 8, result: null },
  { id: 135, matchday: 35, homeTeamId: 16, awayTeamId: 11, result: null },
  { id: 136, matchday: 35, homeTeamId: 18, awayTeamId: 5, result: null },
  { id: 137, matchday: 35, homeTeamId: 20, awayTeamId: 3, result: null },
  { id: 138, matchday: 35, homeTeamId: 15, awayTeamId: 9, result: null },
  { id: 139, matchday: 35, homeTeamId: 17, awayTeamId: 7, result: null },
  { id: 140, matchday: 35, homeTeamId: 19, awayTeamId: 13, result: null },
  // Jornada 36 - Placeholder
  { id: 141, matchday: 36, homeTeamId: 1, awayTeamId: 14, result: null },
  { id: 142, matchday: 36, homeTeamId: 2, awayTeamId: 6, result: null },
  { id: 143, matchday: 36, homeTeamId: 3, awayTeamId: 16, result: null },
  { id: 144, matchday: 36, homeTeamId: 4, awayTeamId: 12, result: null },
  { id: 145, matchday: 36, homeTeamId: 5, awayTeamId: 20, result: null },
  { id: 146, matchday: 36, homeTeamId: 7, awayTeamId: 18, result: null },
  { id: 147, matchday: 36, homeTeamId: 8, awayTeamId: 10, result: null },
  { id: 148, matchday: 36, homeTeamId: 9, awayTeamId: 19, result: null },
  { id: 149, matchday: 36, homeTeamId: 11, awayTeamId: 13, result: null },
  { id: 150, matchday: 36, homeTeamId: 15, awayTeamId: 17, result: null },
  // Jornada 37 - Placeholder
  { id: 151, matchday: 37, homeTeamId: 6, awayTeamId: 8, result: null },
  { id: 152, matchday: 37, homeTeamId: 10, awayTeamId: 1, result: null },
  { id: 153, matchday: 37, homeTeamId: 12, awayTeamId: 3, result: null },
  { id: 154, matchday: 37, homeTeamId: 14, awayTeamId: 5, result: null },
  { id: 155, matchday: 37, homeTeamId: 16, awayTeamId: 7, result: null },
  { id: 156, matchday: 37, homeTeamId: 18, awayTeamId: 9, result: null },
  { id: 157, matchday: 37, homeTeamId: 20, awayTeamId: 11, result: null },
  { id: 158, matchday: 37, homeTeamId: 13, awayTeamId: 2, result: null },
  { id: 159, matchday: 37, homeTeamId: 17, awayTeamId: 4, result: null },
  { id: 160, matchday: 37, homeTeamId: 19, awayTeamId: 15, result: null },
  // Jornada 38 - Placeholder
  { id: 161, matchday: 38, homeTeamId: 1, awayTeamId: 10, result: null },
  { id: 162, matchday: 38, homeTeamId: 2, awayTeamId: 13, result: null },
  { id: 163, matchday: 38, homeTeamId: 3, awayTeamId: 20, result: null },
  { id: 164, matchday: 38, homeTeamId: 4, awayTeamId: 17, result: null },
  { id: 165, matchday: 38, homeTeamId: 5, awayTeamId: 14, result: null },
  { id: 166, matchday: 38, homeTeamId: 7, awayTeamId: 16, result: null },
  { id: 167, matchday: 38, homeTeamId: 8, awayTeamId: 6, result: null },
  { id: 168, matchday: 38, homeTeamId: 9, awayTeamId: 18, result: null },
  { id: 169, matchday: 38, homeTeamId: 11, awayTeamId: 12, result: null },
  { id: 170, matchday: 38, homeTeamId: 15, awayTeamId: 19, result: null },
]
