import type { Team, Match } from "./types"

// Datos iniciales de equipos
export const initialTeams: Team[] = [
  {
    id: 1,
    name: "Pontevedra CF",
    played: 25,
    won: 16,
    drawn: 5,
    lost: 4,
    goalsFor: 35,
    goalsAgainst: 18,
    points: 53,
    logoUrl: "https://cdn.resfu.com/img_data/escudos/medium/1997.jpg?size=35x&lossy=1&ext=jpeg",
  },
  {
    id: 2,
    name: "CD Numancia",
    played: 25,
    won: 14,
    drawn: 9,
    lost: 2,
    goalsFor: 38,
    goalsAgainst: 17,
    points: 51,
    logoUrl: "https://cdn.resfu.com/img_data/escudos/medium/1832.jpg?size=35x&lossy=1",
  },
  {
    id: 3,
    name: "Real Avila",
    played: 26,
    won: 13,
    drawn: 5,
    lost: 8,
    goalsFor: 26,
    goalsAgainst: 17,
    points: 44,
    logoUrl: "https://cdn.resfu.com/img_data/escudos/medium/2094.jpg?size=35x&4",
  },
  {
    id: 4,
    name: "Real Aviles",
    played: 26,
    won: 10,
    drawn: 11,
    lost: 5,
    goalsFor: 35,
    goalsAgainst: 28,
    points: 41,
    logoUrl: "https://cdn.resfu.com/img_data/escudos/medium/2096.jpg?size=35x&4",
  },
  {
    id: 5,
    name: "UP Langreo",
    played: 26,
    won: 10,
    drawn: 8,
    lost: 8,
    goalsFor: 24,
    goalsAgainst: 27,
    points: 38,
    logoUrl: "https://cdn.resfu.com/img_data/escudos/medium/2615.jpg?size=35x&4",
  },
  {
    id: 6,
    name: "Deportivo Fabril",
    played: 25,
    won: 11,
    drawn: 4,
    lost: 10,
    goalsFor: 31,
    goalsAgainst: 21,
    points: 37,
    logoUrl: "https://cdn.resfu.com/img_data/escudos/medium/905.jpg?size=35x&4",
  },
  {
    id: 7,
    name: "Real Valladolid Promesas",
    played: 26,
    won: 9,
    drawn: 10,
    lost: 7,
    goalsFor: 33,
    goalsAgainst: 27,
    points: 37,
    logoUrl: "https://cdn.resfu.com/img_data/escudos/medium/2133.jpg?size=35x&4",
  },
  {
    id: 8,
    name: "Salamanca CF UDS",
    played: 26,
    won: 10,
    drawn: 7,
    lost: 9,
    goalsFor: 35,
    goalsAgainst: 37,
    points: 37,
    logoUrl: "https://cdn.resfu.com/img_data/escudos/medium/2212.jpg?size=35x&4",
  },
  {
    id: 9,
    name: "Bergantiños FC",
    played: 26,
    won: 10,
    drawn: 6,
    lost: 10,
    goalsFor: 38,
    goalsAgainst: 34,
    points: 36,
    logoUrl: "https://cdn.resfu.com/img_data/escudos/medium/479.jpg?size=35x&4",
  },
  {
    id: 10,
    name: "Marino de Luanco",
    played: 26,
    won: 10,
    drawn: 6,
    lost: 10,
    goalsFor: 28,
    goalsAgainst: 26,
    points: 36,
    logoUrl: "https://cdn.resfu.com/img_data/escudos/medium/793.jpg?size=35x&4",
  },
  {
    id: 11,
    name: "Rayo Cantabria",
    played: 26,
    won: 9,
    drawn: 8,
    lost: 9,
    goalsFor: 42,
    goalsAgainst: 37,
    points: 35,
    logoUrl: "https://cdn.resfu.com/img_data/escudos/medium/2117.jpg?size=35x&4",
  },
  {
    id: 12,
    name: "Coruxo FC",
    played: 26,
    won: 8,
    drawn: 6,
    lost: 12,
    goalsFor: 25,
    goalsAgainst: 28,
    points: 30,
    logoUrl: "https://cdn.resfu.com/img_data/escudos/medium/842.jpg?size=35x&4",
  },
  {
    id: 13,
    name: "UD Llanera",
    played: 26,
    won: 7,
    drawn: 8,
    lost: 11,
    goalsFor: 25,
    goalsAgainst: 33,
    points: 29,
    logoUrl: "https://cdn.resfu.com/img_data/escudos/medium/4689.jpg?size=35x&4",
  },
  {
    id: 14,
    name: "Escobedo",
    played: 26,
    won: 6,
    drawn: 10,
    lost: 10,
    goalsFor: 16,
    goalsAgainst: 33,
    points: 28,
    logoUrl: "https://cdn.resfu.com/img_data/escudos/medium/2580.jpg?size=35x&4",
  },
  {
    id: 15,
    name: "SD Compostela",
    played: 25,
    won: 7,
    drawn: 7,
    lost: 11,
    goalsFor: 27,
    goalsAgainst: 32,
    points: 28,
    logoUrl: "https://cdn.resfu.com/img_data/escudos/medium/6206.jpg?size=35x&4",
  },
  {
    id: 16,
    name: "CD Guijuelo",
    played: 26,
    won: 5,
    drawn: 12,
    lost: 9,
    goalsFor: 23,
    goalsAgainst: 30,
    points: 27,
    logoUrl: "https://cdn.resfu.com/img_data/escudos/medium/1271.jpg?size=35x&4",
  },
  {
    id: 17,
    name: "Gimnastica de Torrelavega",
    played: 26,
    won: 4,
    drawn: 9,
    lost: 13,
    goalsFor: 22,
    goalsAgainst: 34,
    points: 21,
    logoUrl: "https://cdn.resfu.com/img_data/escudos/medium/1231.jpg?size=35x&4",
  },
  {
    id: 18,
    name: "Laredo",
    played: 26,
    won: 3,
    drawn: 9,
    lost: 14,
    goalsFor: 19,
    goalsAgainst: 43,
    points: 18,
    logoUrl: "https://cdn.resfu.com/img_data/escudos/medium/1515.jpg?size=35x&4",
  },
]

// Restaurar los datos originales de partidos del frontend
export const initialFixtures: Match[] = [
  // Jornada 20 (nueva)
  { id: 73, matchday: 20, homeTeamId: 1, awayTeamId: 2, result: null },
  { id: 74, matchday: 20, homeTeamId: 15, awayTeamId: 6, result: null },
  // Jornada 27
  { id: 1, matchday: 27, homeTeamId: 11, awayTeamId: 5, result: null },
  { id: 2, matchday: 27, homeTeamId: 14, awayTeamId: 10, result: null },
  { id: 3, matchday: 27, homeTeamId: 2, awayTeamId: 18, result: null },
  { id: 4, matchday: 27, homeTeamId: 9, awayTeamId: 7, result: null },
  { id: 5, matchday: 27, homeTeamId: 13, awayTeamId: 3, result: null },
  { id: 6, matchday: 27, homeTeamId: 8, awayTeamId: 17, result: null },
  { id: 7, matchday: 27, homeTeamId: 12, awayTeamId: 15, result: null },
  { id: 8, matchday: 27, homeTeamId: 16, awayTeamId: 6, result: null },
  { id: 9, matchday: 27, homeTeamId: 4, awayTeamId: 1, result: null },
  // Jornada 28
  { id: 10, matchday: 28, homeTeamId: 7, awayTeamId: 13, result: null },
  { id: 11, matchday: 28, homeTeamId: 6, awayTeamId: 4, result: null },
  { id: 12, matchday: 28, homeTeamId: 14, awayTeamId: 2, result: null },
  { id: 13, matchday: 28, homeTeamId: 15, awayTeamId: 9, result: null },
  { id: 14, matchday: 28, homeTeamId: 17, awayTeamId: 18, result: null },
  { id: 15, matchday: 28, homeTeamId: 5, awayTeamId: 16, result: null },
  { id: 16, matchday: 28, homeTeamId: 1, awayTeamId: 12, result: null },
  { id: 17, matchday: 28, homeTeamId: 3, awayTeamId: 8, result: null },
  { id: 18, matchday: 28, homeTeamId: 10, awayTeamId: 11, result: null },
  // Jornada 29
  { id: 19, matchday: 29, homeTeamId: 9, awayTeamId: 1, result: null },
  { id: 20, matchday: 29, homeTeamId: 2, awayTeamId: 17, result: null },
  { id: 21, matchday: 29, homeTeamId: 12, awayTeamId: 6, result: null },
  { id: 22, matchday: 29, homeTeamId: 16, awayTeamId: 10, result: null },
  { id: 23, matchday: 29, homeTeamId: 18, awayTeamId: 3, result: null },
  { id: 24, matchday: 29, homeTeamId: 13, awayTeamId: 15, result: null },
  { id: 25, matchday: 29, homeTeamId: 11, awayTeamId: 14, result: null },
  { id: 26, matchday: 29, homeTeamId: 4, awayTeamId: 5, result: null },
  { id: 27, matchday: 29, homeTeamId: 8, awayTeamId: 7, result: null },
  // Jornada 30
  { id: 28, matchday: 30, homeTeamId: 15, awayTeamId: 8, result: null },
  { id: 29, matchday: 30, homeTeamId: 6, awayTeamId: 9, result: null },
  { id: 30, matchday: 30, homeTeamId: 14, awayTeamId: 16, result: null },
  { id: 31, matchday: 30, homeTeamId: 5, awayTeamId: 12, result: null },
  { id: 32, matchday: 30, homeTeamId: 10, awayTeamId: 4, result: null },
  { id: 33, matchday: 30, homeTeamId: 1, awayTeamId: 13, result: null },
  { id: 34, matchday: 30, homeTeamId: 11, awayTeamId: 2, result: null },
  { id: 35, matchday: 30, homeTeamId: 3, awayTeamId: 17, result: null },
  { id: 36, matchday: 30, homeTeamId: 7, awayTeamId: 18, result: null },
  // Jornada 31
  { id: 37, matchday: 31, homeTeamId: 9, awayTeamId: 5, result: null },
  { id: 38, matchday: 31, homeTeamId: 12, awayTeamId: 10, result: null },
  { id: 39, matchday: 31, homeTeamId: 17, awayTeamId: 7, result: null },
  { id: 40, matchday: 31, homeTeamId: 16, awayTeamId: 11, result: null },
  { id: 41, matchday: 31, homeTeamId: 18, awayTeamId: 15, result: null },
  { id: 42, matchday: 31, homeTeamId: 6, awayTeamId: 13, result: null },
  { id: 43, matchday: 31, homeTeamId: 2, awayTeamId: 3, result: null },
  { id: 44, matchday: 31, homeTeamId: 4, awayTeamId: 14, result: null },
  { id: 45, matchday: 31, homeTeamId: 8, awayTeamId: 1, result: null },
  // Jornada 32
  { id: 46, matchday: 32, homeTeamId: 15, awayTeamId: 17, result: null },
  { id: 47, matchday: 32, homeTeamId: 6, awayTeamId: 8, result: null },
  { id: 48, matchday: 32, homeTeamId: 14, awayTeamId: 12, result: null },
  { id: 49, matchday: 32, homeTeamId: 16, awayTeamId: 2, result: null },
  { id: 50, matchday: 32, homeTeamId: 5, awayTeamId: 13, result: null },
  { id: 51, matchday: 32, homeTeamId: 10, awayTeamId: 9, result: null },
  { id: 52, matchday: 32, homeTeamId: 1, awayTeamId: 18, result: null },
  { id: 53, matchday: 32, homeTeamId: 11, awayTeamId: 4, result: null },
  { id: 54, matchday: 32, homeTeamId: 7, awayTeamId: 3, result: null },
  // Jornada 33
  { id: 55, matchday: 33, homeTeamId: 9, awayTeamId: 14, result: null },
  { id: 56, matchday: 33, homeTeamId: 12, awayTeamId: 11, result: null },
  { id: 57, matchday: 33, homeTeamId: 17, awayTeamId: 1, result: null },
  { id: 58, matchday: 33, homeTeamId: 18, awayTeamId: 6, result: null },
  { id: 59, matchday: 33, homeTeamId: 13, awayTeamId: 10, result: null },
  { id: 60, matchday: 33, homeTeamId: 3, awayTeamId: 15, result: null },
  { id: 61, matchday: 33, homeTeamId: 4, awayTeamId: 16, result: null },
  { id: 62, matchday: 33, homeTeamId: 8, awayTeamId: 5, result: null },
  { id: 63, matchday: 33, homeTeamId: 7, awayTeamId: 2, result: null },
  // Jornada 34
  { id: 64, matchday: 34, homeTeamId: 15, awayTeamId: 7, result: null },
  { id: 65, matchday: 34, homeTeamId: 6, awayTeamId: 17, result: null },
  { id: 66, matchday: 34, homeTeamId: 14, awayTeamId: 13, result: null },
  { id: 67, matchday: 34, homeTeamId: 16, awayTeamId: 12, result: null },
  { id: 68, matchday: 34, homeTeamId: 5, awayTeamId: 18, result: null },
  { id: 69, matchday: 34, homeTeamId: 10, awayTeamId: 8, result: null },
  { id: 70, matchday: 34, homeTeamId: 2, awayTeamId: 4, result: null },
  { id: 71, matchday: 34, homeTeamId: 1, awayTeamId: 3, result: null },
  { id: 72, matchday: 34, homeTeamId: 11, awayTeamId: 9, result: null },
]

