/**
 * Mapeo de nombres de equipos de BDFutbol a IDs de la app para
 * Primera Federación Grupo 1, temporada 2026/27.
 */
export const teamNameMapping: Record<string, number> = {
  "mirandes": 1,
  "cd mirandes": 1,
  "cultural leonesa": 2,
  "cultural y deportiva leonesa": 2,
  "cyd leonesa": 2,
  "pontevedra": 3,
  "pontevedra cf": 3,
  "bilbao athletic": 4,
  "athletic club b": 4,
  "racing de ferrol": 5,
  "racing ferrol": 5,
  "racing club ferrol": 5,
  "deportivo fabril": 6,
  "rc deportivo fabril": 6,
  "lugo": 7,
  "cd lugo": 7,
  "zamora": 8,
  "zamora cf": 8,
  "aviles industrial": 9,
  "real aviles industrial": 9,
  "aviles": 9,
  "barakaldo": 10,
  "barakaldo cf": 10,
  "merida ad": 11,
  "ad merida": 11,
  "merida": 11,
  "unionistas de salamanca": 12,
  "unionistas de salamanca cf": 12,
  "unionistas cf": 12,
  "unionistas": 12,
  "arenas de getxo": 13,
  "arenas club": 13,
  "arenas": 13,
  "ponferradina": 14,
  "sd ponferradina": 14,
  "ud ourense": 15,
  "real union": 16,
  "real union club": 16,
  "cacereno": 17,
  "cp cacereno": 17,
  "coria": 18,
  "cd coria": 18,
  "extremadura": 19,
  "cd extremadura": 19,
  "ud logrones": 20,
}

export const teamIdToName: Record<number, string> = {
  1: "CD Mirandés",
  2: "CyD Leonesa",
  3: "Pontevedra CF",
  4: "Bilbao Athletic",
  5: "Racing Club Ferrol",
  6: "RC Deportivo Fabril",
  7: "CD Lugo",
  8: "Zamora CF",
  9: "Real Avilés Industrial",
  10: "Barakaldo CF",
  11: "AD Mérida",
  12: "Unionistas de Salamanca CF",
  13: "Arenas Club",
  14: "SD Ponferradina",
  15: "UD Ourense",
  16: "Real Unión Club",
  17: "CP Cacereño",
  18: "CD Coria",
  19: "CD Extremadura",
  20: "UD Logroñés",
}
