import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { MODEL_VERSION } from "@/lib/forecasts/model";
import styles from "../forecast.module.css";

export const metadata: Metadata = {
  title: "Cómo se calculan los pronósticos",
  description: "Fuentes, históricos, simulación de partidos, objetivos de puntos y límites del modelo del Pontevedra CF.",
};

export default function MethodologyPage() {
  return <main className={styles.app}><article className={styles.article}>
    <Link href="/pronosticos" className={styles.back}><ArrowLeft size={17} aria-hidden="true" />Volver al panel</Link>
    <p className={styles.eyebrow}>METODOLOGÍA · {MODEL_VERSION}</p>
    <h1>Qué hay detrás de cada probabilidad.</h1>
    <div className={styles.demo}><span className={styles.demoBadge}>MODELO EXPERIMENTAL</span><span>Las probabilidades son estimaciones matemáticas. Todavía no se ha contrastado su calibración con temporadas fuera de la muestra de ajuste.</span></div>
    <p>La sección Pronósticos de Calculadora Granate combina resultados reales con miles de finales de temporada posibles. Usa el formato de datos de Calculadora Granate y calcula las opciones del Pontevedra en el grupo 1 de Primera Federación.</p>
    <section><h2>1. Tres objetivos diferentes</h2><ul><li><strong>Permanencia:</strong> terminar del 1.º al 15.º.</li><li><strong>Playoff:</strong> acabar del 2.º al 5.º.</li><li><strong>Campeón:</strong> quedar primero.</li></ul><p>Las probabilidades no suman 100 % porque los dos últimos objetivos también incluyen salvarse. Para el objetivo de puntos de playoff usamos el top 5, incluyendo acabar campeón. El modelo no calcula la probabilidad de ganar las eliminatorias de ascenso ni anticipa decisiones administrativas de elegibilidad.</p></section>
    <section><h2>2. De dónde salen los datos</h2><p>La base inicial procede de Calculadora Granate: veinte equipos y los 380 partidos de 2026/27. Se actualiza desde <a href="https://www.bdfutbol.com/es/t/t2026-271rf1.html" target="_blank" rel="noreferrer">BDFutbol</a>, consultando clasificación y calendario completo. Los identificadores se mantienen estables para no duplicar equipos o partidos.</p><p>Conservamos el orden de clasificación publicado por la fuente, que puede cambiar al actualizarse los desempates. Si clasificación y partidos no encajan, rechazamos esa actualización. Si BDFutbol falla, consultamos la clasificación y los resultados de AS, conservando el calendario completo de Calculadora Granate y comprobando que los partidos y los goles coinciden con la tabla. La calculadora y esta sección comparten la misma lectura de datos. Los resultados oficiales guardados en Redis completan los partidos que todavía no tienen marcador en la fuente; no sustituyen resultados ya publicados. La portada identifica la fuente utilizada. Cuando ambas fuentes fallan utilizamos la última copia recuperable del archivo y, si tampoco está disponible, la copia inicial fechada. El aviso de la portada lo indica.</p><p>Las consultas se reutilizan durante una hora. Una visita posterior provoca la actualización de la caché, y hay una actualización automática diaria a las 06:00 UTC. No son resultados en directo. La fecha visible indica cuándo consultamos la fuente, no cuándo el proveedor publicó su información.</p></section>
    <section><h2>3. Cinco temporadas de referencia</h2><p>La muestra contiene las temporadas 2021/22 a 2025/26 de los dos grupos: 3.800 partidos. La tabla histórica muestra los puntos finales de campeón, 5.º, 6.º, 15.º y 16.º. Los enlaces de cada fila permiten consultar la fuente.</p><p>Los puntos del último salvado no constituyen un mínimo universal. Dos equipos pueden terminar con los mismos puntos y tener destinos distintos por los desempates. Se conservan las deducciones de puntos publicadas; no se presentan las repescas posteriores como permanencias deportivas.</p><p>Para estimar el promedio de goles, cada temporada anterior recibe el 80 % del peso de la inmediatamente posterior. El grupo 2 pesa el 80 % del grupo 1. Se excluyen de ese promedio los encuentros de equipos marcados por la fuente con incidencias administrativas, para reducir el efecto de marcadores adjudicados.</p></section>
    <section><h2>4. La fuerza de cada rival</h2><p>Se estiman dos valores por equipo: capacidad ofensiva y facilidad para conceder goles. La referencia inicial combina la media de la división con el rendimiento en Primera Federación de la temporada anterior: se conserva el 35 % de su diferencia respecto a la media. Los equipos sin esa referencia parten de la media, con mayor incertidumbre; todavía no incorporamos su rendimiento en otras categorías.</p><p>Ese punto de partida equivale a dieciséis partidos de referencia. Se añaden los resultados de la temporada actual, ajustados por la fuerza del rival y la localía. Una jornada anterior pesa un 2 % menos que la siguiente. Con dos partidos en las jornadas 1 y 2, la temporada actual aporta aproximadamente el 11 % del peso de esta estimación; con diez jornadas consecutivas, el 36 %. Estos pesos no son porcentajes directos de permanencia o playoff. Los puntos y goles ya conseguidos cuentan íntegramente.</p><p>Se realizan seis actualizaciones de los valores para ajustar la influencia entre rivales. La incertidumbre inicial de ataque y defensa usa una desviación logarítmica de 0,30 con histórico comparable y 0,40 sin él. Se reduce dividiéndola entre la raíz de uno más los partidos ponderados entre doce. Así disminuye gradualmente con la evidencia disponible.</p><p>No se incluyen lesiones, fichajes, alineaciones, presupuestos ni noticias de última hora. Estos parámetros buscan moderar la reacción a pocos partidos, pero siguen pendientes de calibración retrospectiva: no podemos presentarlos como óptimos ni garantizar una mayor precisión.</p></section>
    <section><h2>5. Diez mil finales de temporada</h2><ol><li>Para cada equipo se obtiene una fuerza posible alrededor de su estimación, mediante una variación lognormal de media uno.</li><li>Los goles esperados del local son la media histórica local multiplicada por su ataque y la defensa del visitante. Se hace el cálculo equivalente para el visitante.</li><li>Se generan goles de dos distribuciones Poisson. Las medias se limitan al intervalo 0,08–6 para evitar extremos inestables.</li><li>Cada partido pendiente se resuelve una sola vez por simulación, compartiendo el resultado entre ambos equipos. Los resultados ya disputados permanecen fijos.</li><li>Se suman los puntos y se ordenan los equipos. La fracción de simulaciones en cada zona da su probabilidad.</li></ol><p>El proceso utiliza una semilla reproducible: los mismos datos y versión producen el mismo cálculo. Las variaciones de equipo se mantienen durante toda una simulación para representar trayectorias mejores o peores de lo esperado.</p></section>
    <section><h2>6. Empates y puntos necesarios</h2><p>El desempate simulado sigue los criterios deportivos del <a href="https://rfef.es/sites/default/files/2025-11/TABLA_DE_CORRESPONDENCIA_PARA_PUBLICAR.pdf" target="_blank" rel="noreferrer">artículo 29 del Reglamento de Competiciones de la RFEF</a>: diferencia particular entre dos equipos; miniliga por puntos y diferencia de goles entre más de dos; después diferencia global y goles marcados. Cuando se separa un equipo de un empate múltiple, se reaplican los criterios al subgrupo restante.</p><p>No conocemos las futuras puntuaciones de juego limpio. Si todos los criterios deportivos dejan igualdad, repartimos aleatoriamente el orden restante en las simulaciones. Es una aproximación explícita, no una reproducción de una futura decisión federativa.</p><p>Para cada puntuación final exacta del Pontevedra contamos cuántos escenarios cumplen el objetivo. Solo consideramos puntuaciones con al menos cien observaciones y exigimos que el límite inferior del intervalo de Wilson al 95 % sea al menos el 90 %. La primera puntuación que cumple esto es el objetivo orientativo. Si no hay muestra suficiente, no se ofrece un número.</p><p>El objetivo depende de los escenarios del modelo: no garantiza salvarse o clasificarse con esa puntuación en cualquier combinación de resultados. Los puntos que faltan son objetivo menos puntos actuales; el ritmo necesario divide esa diferencia entre los partidos pendientes.</p><p>El corte del grupo es otra medida: la mediana y el intervalo central del 80 % de los puntos del 15.º, 5.º o 1.º. No debe confundirse con el objetivo particular del Pontevedra.</p></section>
    <section><h2>7. Escenarios y evolución</h2><p>Puedes importar desde la calculadora un escenario con resultados pendientes. Esos resultados cambian simultáneamente los puntos del local y visitante. Los demás encuentros se vuelven a simular con el mismo modelo y semilla, sin modificar los resultados reales.</p><p>El cálculo del escenario se ejecuta en un trabajador del navegador para mantener la página disponible. Las fuerzas se mantienen en su estimación actual: fijar una victoria no presupone además que el equipo se haya vuelto más fuerte.</p><p>Las predicciones reales se guardan como documentos inmutables con sus datos, fecha, semilla y versión. El gráfico presenta el último registro de cada jornada dentro de la misma versión. No se rellenan jornadas anteriores con información posterior, y no se mezclan porcentajes de versiones distintas. Un cambio de versión inicia una nueva serie, conservando los registros antiguos.</p><p>La variación se expresa en puntos porcentuales: pasar del 80 % al 86 % equivale a subir 6 puntos porcentuales. Los escenarios hipotéticos no se guardan en el historial real.</p></section>
    <section><h2>8. Cómo interpretar los límites</h2><p>Una probabilidad del 100 % en diez mil simulaciones solo significa que el objetivo se cumplió en todas ellas. No demuestra permanencia o campeonato matemáticos. Tampoco un 0 % demuestra imposibilidad si existen desenlaces muy poco frecuentes.</p><p>El número de simulaciones reduce el ruido del cálculo, pero no corrige sesgos de los datos ni errores del modelo. La calibración retrospectiva sigue pendiente: hasta realizarla, esta aplicación debe entenderse como una herramienta orientativa para explorar el calendario.</p></section>
    <footer className={styles.footer}><span>Calculadora Granate · {MODEL_VERSION}</span><Link href="/pronosticos">Volver al panel</Link></footer>
  </article></main>;
}
